export const listBookDummie = [
  {
    id: 3,
    isbn: "195153448",
    title: "Wallis",
    authors: ["Anne Edwards"],
    languageCode: "en",
    genre: ["Historical", "Historical Fiction", "Fiction", "Novels"],
    publisher: "Oxford University Press",
    publishedDate: "1991-01-01",
    pageCount: 478,
    size: "15.5x20.5",
  },
  {
    id: 6,
    isbn: "2005018",
    title: "From Potter's Field",
    authors: ["Patricia Daniels Cornwell"],
    languageCode: "en",
    genre: [
      "Mystery",
      "Fiction",
      "Mystery",
      "Crime",
      "Thriller",
      "Thriller",
      "Mystery Thriller",
      "Suspense",
      "Mystery",
      "Murder Mystery",
      "Mystery",
      "Detective",
      "Adult",
      "Audiobook",
    ],
    publisher: "Oxford University Press",
    publishedDate: "1995-01-01",
    pageCount: 340,
    size: "15.5x20.5",
  },
  {
    id: 10,
    isbn: "60973129",
    title: "Deep Waters",
    authors: ["Barbara Nadel"],
    languageCode: "en",
    genre: ["Mystery", "Mystery", "Crime", "Fiction"],
    publisher: "Oxford University Press",
    publishedDate: "2002-01-01",
    pageCount: 441,
    size: "15.5x20.5",
  },
  {
    id: 20,
    isbn: "374157065",
    title: "Foundling",
    authors: ["June Oldham"],
    languageCode: "en",
    genre: [
      "Science Fiction",
      "Childrens",
      "Science Fiction",
      "Dystopia",
      "Fiction",
      "Young Adult",
    ],
    publisher: "Oxford University Press",
    publishedDate: "1995-01-01",
    pageCount: 215,
    size: "15.5x20.5",
  },
];
